version: "3.4"
services:
  spark-notebook:
    image: jupyter/pyspark-notebook:python-3.8
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOSTNAME=kafka
      - KAFKA_PORT=9092
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
    - kafka
    - postgres
    healthcheck:
      start_period: 10s
  monitor:
    build:
      context: monitor
      dockerfile: Dockerfile
      args:
        - environment=compose
    restart: on-failure
    links:
      - kafka
    depends_on:
      - backend
volumes:
  pgdata: {}
  kafka_data:
    driver: local
